# Generated by Django 4.2.11 on 2024-04-25 13:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea3', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stop',
            name='seats_booked',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='train',
            name='seats_count',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Seat',
        ),
    ]
