# Generated by Django 4.2.11 on 2024-04-25 19:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea3', '0002_stop_seats_booked_train_seats_count_delete_seat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='seats_booked',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
