# Generated by Django 4.2.11 on 2024-04-25 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idea3', '0003_alter_stop_seats_booked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='stop',
            name='station_name',
        ),
        migrations.AlterField(
            model_name='stop',
            name='arrival_time',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='train',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='stop',
            name='station',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='idea3.station'),
            preserve_default=False,
        ),
    ]
