# Generated by Django 4.2.11 on 2024-04-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='seat_id',
            new_name='seat',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='train_id',
            new_name='train',
        ),
        migrations.RenameField(
            model_name='seat',
            old_name='stop_id',
            new_name='stop',
        ),
        migrations.RenameField(
            model_name='seat',
            old_name='train_id',
            new_name='train',
        ),
        migrations.RenameField(
            model_name='stop',
            old_name='train_id',
            new_name='train',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='booking_id',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='seat_id',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='stop_id',
        ),
        migrations.RemoveField(
            model_name='train',
            name='train_id',
        ),
        migrations.AddField(
            model_name='booking',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seat',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stop',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='train',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
