volumes:
  postgres_data:

# networks:
#   app_net:
#     driver: bridge

services:
  web:
    build: .
    command: gunicorn trainBooking.wsgi:application --bind 0.0.0.0:8000
    # networks:
    #   - app_net
    # ports:
    #   - "8000:8000"

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: train-booking
      POSTGRES_USER: train-admin
      POSTGRES_PASSWORD: train-admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # networks:
    #   - app_net


  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - web
    # networks:
    #   - app_net
