volumes:
  postgres_data:

services:
  web1:
    build: .
    command: gunicorn trainBooking.wsgi:application --bind 0.0.0.0:8000 -w 3
    ports:
      - 9000:8000
    environment:
      DATABASE_URL: psql://train-admin:train-admin@db/train-booking
  web2:
    build: .
    command: gunicorn trainBooking.wsgi:application --bind 0.0.0.0:8000 -w 3
    environment:
      DATABASE_URL: psql://train-admin:train-admin@db/train-booking
  web3:
    build: .
    command: gunicorn trainBooking.wsgi:application --bind 0.0.0.0:8000 -w 3
    environment:
      DATABASE_URL: psql://train-admin:train-admin@db/train-booking

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: train-booking
      POSTGRES_USER: train-admin
      POSTGRES_PASSWORD: train-admin
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - web1
      - web2
      - web3
