# Generated by Django 4.2.11 on 2024-04-22 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('train_id', models.AutoField(primary_key=True, serialize=False)),
                ('train_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('stop_id', models.AutoField(primary_key=True, serialize=False)),
                ('station_name', models.CharField(max_length=100)),
                ('arrival_time', models.DateTimeField()),
                ('departure_time', models.DateTimeField()),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainInfo.train')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('seat_id', models.AutoField(primary_key=True, serialize=False)),
                ('seat_number', models.CharField(max_length=10)),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainInfo.train')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_date', models.DateTimeField()),
                ('journey_end_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_booking', to='trainInfo.stop')),
                ('journey_start_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_booking', to='trainInfo.stop')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainInfo.seat')),
            ],
        ),
    ]
