# Generated by Django 4.2.11 on 2024-04-22 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainInfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='station_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
